export const HEADER_HEIGHT = 60;

export const dataMock = {
    Id: 1750579777260,
    RequesterId: 10,
    Title: "Khao sat",
    Description: "asasa",
    MarketSurveyVersionStatusId: 2,
    SurveyTypeId: 2,
    SurveyTopicId: 2,
    SurveySpecificTopicId: 5,
    SurveyStatusId: 1,
    SecurityModeId: 2,
    BackgroundImageBase64: "",
    IsSuccess: true,
    ConfigJson: {
        Background: "image",
        IsUseBackgroundImageBase64: false,
        BackgroundGradient1Color: "#ffffff",
        BackgroundGradient2Color: "#f0f0f0",
        TitleColor: "#2f2f2f",
        ContentColor: "#444444",
        ButtonBackgroundColor: "#027186",
        ButtonContentColor: "#FEC347",
        Password: "123456",
        Brightness: 100,
        DefaultBackgroundImageId: 8,
        SkipStartPage: false,
    },
    Questions: [
        {
            Id: 11,
            QuestionTypeId: 1,
            Content: "C1",
            Description: "c1",
            TimeLimit: 12,
            IsVoice: false,
            Order: 1,
            ConfigJson: {
                JumpLogics: [
                    {
                        Conditions: [
                            {
                                QuestionId: 11,
                                Conjunction: null,
                                Operator: "Chọn",
                                OptionId: 1,
                                CompareValue: 0,
                            },
                            // {
                            //     QuestionId: 22,
                            //     Conjunction: "AND",
                            //     Operator: "Chọn",
                            //     OptionId: 1,
                            //     CompareValue: 0,
                            // },
                        ],
                        TargetQuestionId: 55,
                    },
                ],
            },
            Options: [
                {
                    Id: 1,
                    Content: "a",
                    Order: 1,
                },
                {
                    Id: 2,
                    Content: "b",
                    Order: 2,
                },
                {
                    Id: 3,
                    Content: "c",
                    Order: 3,
                },
            ],
        },
        {
            Id: 22,
            QuestionTypeId: 2,
            Content: "C2",
            Description: "2",
            TimeLimit: 0,
            IsVoice: false,
            Order: 2,
            ConfigJson: {},
            Options: [
                {
                    Id: 1,
                    Content: "a",
                    Order: 1,
                },
                {
                    Id: 2,
                    Content: "b",
                    Order: 2,
                },
            ],
        },
        {
            Id: 33,
            QuestionTypeId: 3,
            Content: "c3",
            Description: "c3",
            TimeLimit: 0,
            IsVoice: false,
            Order: 3,
            ConfigJson: {
                Min: 0,
                Max: 10,
                Step: 1,
                Unit: "",
            },
            Options: [],
        },
        {
            Id: 44,
            QuestionTypeId: 4,
            Content: "c4",
            Description: "c4",
            TimeLimit: 0,
            IsVoice: false,
            Order: 4,
            ConfigJson: {
                Min: 1,
                Max: 10,
                Step: 1,
                Unit: "",
            },
            Options: [],
        },
        {
            Id: 55,
            QuestionTypeId: 6,
            Content: "c5",
            Description: "c5",
            TimeLimit: 0,
            IsVoice: false,
            Order: 5,
            ConfigJson: {
                RatingIcon: "FreeBreakfastIcon",
                RatingLength: 8,
            },
            Options: [],
        },
        {
            Id: 66,
            QuestionTypeId: 7,
            Content: "c6",
            Description: "c6",
            TimeLimit: 0,
            IsVoice: false,
            Order: 6,
            ConfigJson: {},
            Options: [
                {
                    Id: 1,
                    Content: "a",
                    Order: 1,
                },
                {
                    Id: 2,
                    Content: "b",
                    Order: 2,
                },
                {
                    Id: 3,
                    Content: "c",
                    Order: 3,
                },
                {
                    Id: 4,
                    Content: "d",
                    Order: 4,
                },
            ],
        },
        {
            Id: 77,
            QuestionTypeId: 5,
            Content: "",
            Description: "",
            TimeLimit: 0,
            IsVoice: false,
            Order: 7,
            ConfigJson: {
                FieldInputTypeId: 9,
            },
            Options: [],
        },
    ],
    type: "update",
};
